FROM node:10 as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG API_URI
ARG SENTRY_DSN
ARG SENTRY_APM
ARG DEMO_MODE
ARG GTM_ID
ARG ALGOLIA_APPLICATION_ID
ARG ALGOLIA_SEARCH_KEY
ENV API_URI ${API_URI:-http://localhost:8000/graphql/}

ENV ALGOLIA_APPLICATION_ID ${ALGOLIA_APPLICATION_ID}
ENV ALGOLIA_SEARCH_KEY ${ALGOLIA_SEARCH_KEY}

RUN API_URI=${API_URI} ALGOLIA_APPLICATION_ID=${ALGOLIA_APPLICATION_ID} ALGOLIA_SEARCH_KEY=${ALGOLIA_SEARCH_KEY} npm run build

FROM nginx:stable
WORKDIR /app
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/ /app/
